language: go

go:
  - 1.12.2

env:
  global:
    - GO111MODULE=on

os:
  - linux
  - osx
  - windows

before_script: go version

script:
  - go test ${gobuild_args} ./...
  - go test ${gobuild_args} ./... -bench '.*'
