language: go

go:
  - 1.12.2

os:
  - linux
  - osx
  - windows

before_script: go version

script:
  - env GO111MODULE=on go test ${gobuild_args} ./...
  - env GO111MODULE=on go test ${gobuild_args} ./... -bench '.*'
